config/routes.rb
Rails.application.routes.draw do

	root "produtos#index"

	# rotas de produtos - exemplos
	post "produtos", to: "produtos#create"
	get "produtos", to: "produtos#index"
	get "produtos/formulario", to: "produtos#formulario"
	
	# rotas de passagens
	post "passagens", to: "passagens#create"
	get "passagens", to: "passagens#index"
	
	# rotas de hospedagens
	post "hospedagens", to: "hospedagens#create"
	get "hospedagens", to: "hospedagens#index"

	# rotas de pacote
	post "pacotes", to: "pacotes#create"
	get "pacotes", to: "pacotes#index"

	get "respostas", to: "respostas#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agturismo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
 	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>

  <body>
  	<%= nav_bar brand: "Turismo", brand_link: produtos_path do %>
  		<%= menu_group do %>
        <%= drop_down "Passagem" do %>
  			  <%= menu_item "Consultar passagem", passagens_path + "?funcao=consultar" %>
  			  <%= menu_item "Comprar passagem", passagens_path + "?funcao=comprar" %>
        <% end %>
        <%= drop_down "Hospedagem" do %>
          <%= menu_item "Consultar hospedagem", hospedagens_path + "?funcao=consultar" %>
  			  <%= menu_item "Comprar hospedagem", hospedagens_path + "?funcao=comprar" %>
        <% end %>
        <%= drop_down "Pacote" do %>
          <%= menu_item "Consultar pacote", pacotes_path + "?funcao=consultar" %>
          <%= menu_item "Comprar pacote", pacotes_path + "?funcao=comprar" %>
  		  <% end %>
      <% end %>
	<% end %>
  	<div class="container">
    	<%= yield %>
	</div>
  </body>
</html>